In [175]:
import json
import numpy as np
from sklearn.metrics import classification_report, accuracy_score, f1_score, roc_auc_score
from scipy.stats import spearmanr

In [176]:
def eval(path, threshold:int=0.5):
    
    simbert_test = json.load(open(path))

    sims_np = np.array(simbert_test['sims'])
    pred_np = np.asarray(sims_np > threshold, dtype=np.int32)
    true_np = np.asarray(simbert_test['label'])
    # print(classification_report(true_np, pred_np),accuracy_score(true_np, pred_np), f1_score(true_np, pred_np))

In [210]:
eval('./tmp_data/supSBERT_RDropout_simbert_batchSize16_test', 0.65)

              precision    recall  f1-score   support

           0       0.89      0.76      0.82       904
           1       0.86      0.94      0.89      1377

    accuracy                           0.87      2281
   macro avg       0.87      0.85      0.86      2281
weighted avg       0.87      0.87      0.87      2281
 0.8671635247698378 0.8948281846581048


In [189]:
eval('./tmp_data/supSBERT_simbert_batchSize32_test', 0.65)

              precision    recall  f1-score   support

           0       0.86      0.74      0.79       904
           1       0.84      0.92      0.88      1377

    accuracy                           0.85      2281
   macro avg       0.85      0.83      0.84      2281
weighted avg       0.85      0.85      0.85      2281
 0.8491889522139413 0.8808864265927977


In [205]:
eval('./tmp_data/supSBERT_simbert_batchSize128_test', 0.68)

              precision    recall  f1-score   support

           0       0.87      0.76      0.81       904
           1       0.85      0.92      0.89      1377

    accuracy                           0.86      2281
   macro avg       0.86      0.84      0.85      2281
weighted avg       0.86      0.86      0.86      2281
 0.8592722490135906 0.8879581151832461


In [42]:
eval('./tmp_data/supSimCSE_batchSize64_roformerSim_test', 0.65)

              precision    recall  f1-score   support

           0       0.83      0.77      0.80       976
           1       0.85      0.90      0.87      1448

    accuracy                           0.84      2424
   macro avg       0.84      0.83      0.83      2424
weighted avg       0.84      0.84      0.84      2424
 0.8428217821782178 0.8718466195761858


In [49]:
eval('./tmp_data/supSimCSE_simbert_batchSize64_test', 0.62)

              precision    recall  f1-score   support

           0       0.83      0.70      0.76       976
           1       0.82      0.90      0.86      1448

    accuracy                           0.82      2424
   macro avg       0.83      0.80      0.81      2424
weighted avg       0.82      0.82      0.82      2424
 0.8238448844884488 0.8598621595011487


In [26]:
eval('./tmp_data/simbert_test', 0.55) # 768

              precision    recall  f1-score   support

           0       0.50      0.80      0.62      8662
           1       0.72      0.40      0.51     11313

    accuracy                           0.57     19975
   macro avg       0.61      0.60      0.56     19975
weighted avg       0.63      0.57      0.56     19975
 0.5706132665832291 0.511365578533584


In [28]:
eval('./tmp_data/simbert_whitening_test', 0.55) # 

              precision    recall  f1-score   support

           0       0.77      0.57      0.65      8662
           1       0.72      0.87      0.79     11313

    accuracy                           0.74     19975
   macro avg       0.75      0.72      0.72     19975
weighted avg       0.74      0.74      0.73     19975
 0.737622027534418 0.7892556998673047


In [63]:
eval('./tmp_data/roformer_sim_ft_test', 0.71)

              precision    recall  f1-score   support

           0       0.74      0.61      0.67      8662
           1       0.74      0.83      0.78     11313

    accuracy                           0.74     19975
   macro avg       0.74      0.72      0.72     19975
weighted avg       0.74      0.74      0.73     19975
 0.7367709637046308 0.782151143520053


In [33]:
eval('./tmp_data/roformer_sim_test', 0.55)

              precision    recall  f1-score   support

           0       0.86      0.45      0.59      8662
           1       0.69      0.94      0.80     11313

    accuracy                           0.73     19975
   macro avg       0.77      0.70      0.70     19975
weighted avg       0.76      0.73      0.71     19975
 0.7296620775969962 0.7977073499662846


In [63]:
eval('./tmp_data/roformer_sim_whitening_test', 0.55)

              precision    recall  f1-score   support

           0       0.77      0.56      0.65      8662
           1       0.72      0.87      0.79     11313

    accuracy                           0.74     19975
   macro avg       0.74      0.71      0.72     19975
weighted avg       0.74      0.74      0.73     19975
 0.7352690863579474 0.7878350184561066


In [3]:
from roformer import RoFormerForCausalLM, RoFormerConfig
from transformers import BertTokenizer
import torch
from .utils import util

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
pretrained_model = "junnyu/roformer_chinese_sim_char_base"
tokz = BertTokenizer.from_pretrained(pretrained_model)
config = RoFormerConfig.from_pretrained(pretrained_model)
config.is_decoder = True
config.eos_token_id = tokz.sep_token_id
config.pooler_activation = "linear"
config.output_hidden_states = True
roformer_sim = RoFormerForCausalLM.from_pretrained(pretrained_model, config=config)
roformer_sim.to(device)
roformer_sim.eval()

test_iter = util.get_paired_dataIter('./data/merged_qq_test.csv', tokz, device, 3)

ImportError: attempted relative import with no known parent package

In [115]:
a = torch.ones(10)
isinstance(a, torch.Tensor)
np.clip(a, 1e-8, np.inf)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [127]:
a = np.ones((3,4))
b = np.zeros((2,4))
l = []

In [128]:
l.extend(a.flatten())
l.extend(b.flatten())

In [123]:
np.concatenate([a,b],axis=0).copy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [187]:
c = torch.randn((4,4,))
eye_mask = torch.eye((4)) * -1e12
d = eye_mask + c


In [188]:
torch.nn.functional.softmax(d, dim=1)

tensor([[0.0000, 0.3248, 0.2401, 0.4351],
        [0.5171, 0.0000, 0.3862, 0.0967],
        [0.5216, 0.0608, 0.0000, 0.4176],
        [0.2576, 0.1257, 0.6168, 0.0000]])

In [220]:
from torch.nn import CrossEntropyLoss
loss = CrossEntropyLoss(reduction='none')

In [193]:
np.array([[0,1,0,0], [1,0,0,0],[0,0,0,1],[0,0,1,0]])

[1, 0, 3, 2]

t = torch.arange(4)
t

tensor([0, 1, 2, 3])

In [210]:
labels = torch.hstack([ti for t1_t2 in zip(t[1::2], t[0::2]) for ti in t1_t2])
labels

tensor([1, 0, 3, 2])

In [212]:
proba = torch.nn.functional.softmax(d, dim=1)
proba

tensor([[0.0000, 0.3248, 0.2401, 0.4351],
        [0.5171, 0.0000, 0.3862, 0.0967],
        [0.5216, 0.0608, 0.0000, 0.4176],
        [0.2576, 0.1257, 0.6168, 0.0000]])

In [215]:
index = labels[:, None] == torch.arange(4)[None, :]
index

tensor([[False,  True, False, False],
        [ True, False, False, False],
        [False, False, False,  True],
        [False, False,  True, False]])

In [218]:
proba[index].log()

tensor([-1.1247, -0.6595, -0.8732, -0.4832])

In [222]:
loss(d, labels)

tensor([1.1247, 0.6595, 0.8732, 0.4832])

In [4]:
import torch

In [38]:
batchSize=3
seqLen=5
hidden_nums=4
a = torch.ones(batchSize,hidden_nums)
b = torch.zeros(batchSize,hidden_nums)
a_and_b = torch.concat([a,b], dim=-1)
a_and_b

tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])

In [40]:
0 + torch.ones(1)

tensor([1.])

In [39]:
a_and_b.view(batchSize*2, hidden_nums)

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.]])

In [32]:
a_and_b.view(4,2,3)

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])

In [ ]:
# 1. simCSE 
## 1.1 simCSE + whitening(368)
# 2. supervised
## 2.1 SBERT 
## 2.2 SBERT + R-dropout(监督)
## 2.3 SBERT + Info-NCE(多个neg_sample)
## 2.4 SBERT + R-dropout + Info-NCE

In [44]:
a_gpu = a.cuda()


In [45]:
torch.matmul(a_gpu, a_gpu.T)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], device='cuda:0')

In [47]:
a.to(a_gpu.device)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [52]:
for i in range(0, 6, 3):
    print(i)

0
3


In [53]:
from torch import nn
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.w = nn.Parameter(torch.randn(2,1))
        self.b = nn.Parameter(torch.zeros(1,1))

    def forward(self, x):
        y = x@self.w + self.b
        return y

net = Net()

In [67]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter('../data/tensorboard')
writer.add_graph(net,input_to_model = torch.ones(10,2))
writer.add_graph(net,input_to_model = torch.ones(10,2))
writer.close()

In [68]:
%load_ext tensorboard
#%tensorboard --logdir ../data/tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [69]:
from tensorboard import notebook
notebook.list() 

Known TensorBoard instances:
  - port 6006: logdir ../data/tensorboard (started 0:03:19 ago; pid 1060)


In [70]:
#在tensorboard中查看模型
notebook.start("--logdir ../data/tensorboard")

Reusing TensorBoard on port 6006 (pid 1060), started 0:03:20 ago. (Use '!kill 1060' to kill it.)

In [81]:
import torch 
w = torch.tensor([[3.0,1.0]],requires_grad=True)
b = torch.tensor([[3.0]],requires_grad=True)
X = torch.randn(10,2)
Y = torch.randn(10,1)
Y_hat = X@w.t() + b  # Y_hat定义后其正向传播被立即执行，与其后面的loss创建语句无关
Y_hat.retain_grad()
loss = torch.mean(torch.pow(Y_hat-Y,2))

#计算图在反向传播后立即销毁，如果需要保留计算图, 需要设置retain_graph = True
loss.backward()  
# loss.backward(retain_graph = True) 
# loss.backward() #如果再次执行反向传播将报错

In [ ]:
# 先尝试一下forward拆分

In [129]:
a = torch.ones(1)
b = torch.full(size=(1,), fill_value=2., requires_grad=True)

a_and_b = torch.concat([a,b], dim=0)
a_and_b

tensor([1., 2.], grad_fn=<CatBackward0>)

In [134]:
y = a_and_b ** 2
y

tensor([1., 4.], grad_fn=<PowBackward0>)

In [136]:
y.sum().backward()

In [138]:
b.grad, a.grad

(tensor([4.]), None)

In [124]:
k = torch.ones(1, requires_grad=True)
y = k ** 2

In [125]:
y.backward()

In [1]:
from torch import nn
from transformers import BertConfig, BertModel, BertTokenizer, BertForSequenceClassification, AdamW
import torch

def L2_norm(vecs):

    if isinstance(vecs, torch.Tensor):
        norms = (vecs**2).sum(dim=1, keepdims=True).sqrt()
        return vecs / torch.clamp(norms, 1e-8, )
    elif isinstance(vecs, np.ndarray):
        norms = (vecs**2).sum(axis=1, keepdims=True)**0.5
        return vecs / np.clip(norms, 1e-8, np.inf)

class SimCSELoss1(nn.CrossEntropyLoss):

    def _create_sim_labels(self, sents_vecs):

        sample_nums = sents_vecs.shape[0]   # sample_nums = batchSize * 2
        idxs = torch.arange(sample_nums)
        labels = torch.hstack([i for i1_i2 in zip(idxs[1::2], idxs[::2]) for i in i1_i2])
        labels = labels.to(sents_vecs.device)
        
        return labels

    def _cal_masked_sent_sims(self, sents_vecs):

        sents_vecs = L2_norm(sents_vecs) # (batchSize*2, hidden_nums)
        sents_sims = torch.matmul(sents_vecs, sents_vecs.T) 

        sample_nums = sents_sims.shape[0]
        eye_mask = torch.eye(sample_nums) * -1e12
        eye_mask = eye_mask.to(sents_sims.device)
        masked_sents_sims = sents_sims + eye_mask

        return masked_sents_sims

    def forward(
        self, 
        sents_vecs:torch.Tensor,
        reduction:int = 'mean',
    ):
        '''
        sents_vecs: (batchSize*2, hidden_nums)

        - Detailed:
            - s_{2j=1} and s_{2j} are the similar ones
        '''

        masked_sents_sims = self._cal_masked_sent_sims(sents_vecs) # (batchSize*2, hidden_nums)
        labels = self._create_sim_labels(sents_vecs) # (batchSize*2, ) [constractive learning]
        self.reduction = reduction
        loss = super(SimCSELoss1, self).forward(masked_sents_sims, labels)
        return loss

class SimCSELoss2(nn.CrossEntropyLoss):

    def _create_sim_labels(self, sents_vecs):

        sample_nums = sents_vecs.shape[0]   # sample_nums = batchSize * 2
        idxs = torch.arange(sample_nums)
        labels = torch.hstack([i for i1_i2 in zip(idxs[1::2], idxs[::2]) for i in i1_i2])
        labels = labels.to(sents_vecs.device)
        return labels

    def _cal_masked_sent_sims(self, sub_sents_vecs, sents_vecs):
        '''
        :@param sub_sents_vecs: (subSampleSize, hidden_nums)
        :@param sents_vecs: (batchSize*2 | sampleSize, hidden_nums)

        Return:
        sub_masked_sents_sims: (subSampleSize, hidden_nums)
        '''
        
        sub_sents_sims = torch.matmul(sub_sents_vecs, sents_vecs.T) 
        sub_sample_size, batch_size = sub_sents_sims.shape
        
        eye_mask = torch.eye(sub_sample_size) * -1e12   #(subSampleSize, subSampleSize)
        mask = torch.concat([eye_mask, torch.zeros((sub_sample_size, (batch_size - sub_sample_size)))], dim=1)  #(subSampleSize, batchSize)
        mask = mask.to(sub_sents_sims.device)

        sub_masked_sents_sims = sub_sents_sims + mask
        return sub_masked_sents_sims

    def forward(
        self, 
        sents_vecs:torch.Tensor,
        batch_split:int = 2,
        reduction:str = 'none',
    ):
        '''
        sents_vecs: (batchSize*2, hidden_nums)

        - Detailed:
            - s_{2j=1} and s_{2j} are the similar ones
        '''
        self.reduction = 'none'
        sample_size = sents_vecs.shape[0]   # sample_size == batchSize * 2
        print(sample_size)
        assert (sample_size % batch_split == 0) and (sample_size // batch_split % 2 ==0)    
        # sents_vecs could be deviced into each part with the same number in it
        # In each part, the number of sample sould even rather odd
        
        tot_labels = self._create_sim_labels(sents_vecs)    # (batchSize, )
        sents_vecs = L2_norm(sents_vecs)   # (batchSize*2, hidden_nums)

        loss = []
        for i in range(0, sample_size, batch_split):
            start = int(i)
            end = int(i+batch_split)
            sub_sents_vecs = sents_vecs[start:end]
            sub_masked_sent_sims = self._cal_masked_sent_sims(sub_sents_vecs, sents_vecs)   #(subSampleSize, batchSize)
            sub_labels = tot_labels[start:end]    #(subSampleSize, )
            sub_loss = super(SimCSELoss2, self).forward(sub_masked_sent_sims, sub_labels)   # (subSampleSize, )
            loss.append(sub_loss)

        assert end == sample_size

        loss = torch.concat(loss, dim=0)
        if reduction == 'none':
            return loss
        elif reduction == 'mean':
            return loss.mean()
        elif reduction == 'sum':
            return loss.sum()

class SimCSELoss(nn.CrossEntropyLoss):

    def _create_sim_labels(self, sents_vecs):

        sample_nums = sents_vecs.shape[0]   # sample_nums = batchSize * 2
        idxs = torch.arange(sample_nums)
        labels = torch.hstack([i for i1_i2 in zip(idxs[1::2], idxs[::2]) for i in i1_i2])
        labels = labels.to(sents_vecs.device)
        return labels

    def _cal_masked_sent_sims(self, sub_sents_vecs, sents_vecs):
        '''
        :@param sub_sents_vecs: (subSampleSize, hidden_nums)
        :@param sents_vecs: (batchSize*2 | sampleSize, hidden_nums)

        Return:
        sub_masked_sents_sims: (subSampleSize, hidden_nums)
        '''
        
        sub_sents_sims = torch.matmul(sub_sents_vecs, sents_vecs.T) 
        sub_sample_size, batch_size = sub_sents_sims.shape
        
        eye_mask = torch.eye(sub_sample_size) * -1e12   #(subSampleSize, subSampleSize)
        mask = torch.concat([eye_mask, torch.zeros((sub_sample_size, (batch_size - sub_sample_size)))], dim=1)  #(subSampleSize, batchSize)
        mask = mask.to(sub_sents_sims.device)

        sub_masked_sents_sims = sub_sents_sims + mask
        return sub_masked_sents_sims

    def forward(
        self, 
        start:int,
        end:int,
        sents_vecs:torch.Tensor,
        batch_split:int = 2,
        reduction:str = 'none',
    ):
        '''
        sents_vecs: (batchSize*2, hidden_nums)

        - Detailed:
            - s_{2j=1} and s_{2j} are the similar ones
        '''
        self.reduction = 'none'
        tot_labels = self._create_sim_labels(sents_vecs)    # (batchSize, )
        sents_vecs = L2_norm(sents_vecs)   # (batchSize*2, hidden_nums)

        sub_sents_vecs = sents_vecs[start:end, :]
        sub_labels = tot_labels[start:end]

        sub_masked_sent_sims = self._cal_masked_sent_sims(sub_sents_vecs, sents_vecs) 
        sub_loss = super(SimCSELoss, self).forward(sub_masked_sent_sims, sub_labels)

        if reduction == 'none':
            return sub_loss
        elif reduction == 'mean':
            return sub_loss.mean()
        elif reduction == 'sum':
            return sub_loss.sum()

tokz = BertTokenizer.from_pretrained('bert-base-chinese')
bert = BertModel.from_pretrained('bert-base-chinese')
optimizer = AdamW(bert.parameters(), lr=1e-5)
criterion = SimCSELoss1()
bert.cuda()

Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
d:\conda\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future vers

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [13]:
bert

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(21128, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [3]:
batchSize = 32
for i in range(300):
    concat_output = []
    concat_sent1 = []
    concat_sent2 = []
    for _ in range(1):
        text = '我就是来测试一下，不会带有什么目的，纯粹的测试文档'
        texts = [text[:] for _ in range(batchSize)]
        batchData = tokz(texts, padding=True, return_tensors='pt').to(bert.device)

        sent_vecs_1 = bert(**batchData).pooler_output
        sent_vecs_2 = bert(**batchData).pooler_output

        concat_sent1.append(sent_vecs_1)
        concat_sent2.append(sent_vecs_2)

        print(_)
    concat_sent1 = torch.concat(concat_sent1, dim=0)
    concat_sent2 = torch.concat(concat_sent2, dim=0)

    batchSize, hidden_nums = concat_sent1.shape
    combined_sent_vecs = torch.concat([concat_sent1, concat_sent2], dim=-1) # (batchSize, hidden_nums*2)
    combined_sent_vecs = combined_sent_vecs.view(batchSize*2, hidden_nums) # (batchSize*2, hidden_nums)

    loss = criterion(combined_sent_vecs,reduction='mean')
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    print(f'epoch #: {i}')



0
epoch #: 0
0
epoch #: 1
0
epoch #: 2
0
epoch #: 3
0
epoch #: 4
0
epoch #: 5
0
epoch #: 6
0
epoch #: 7
0
epoch #: 8
0
epoch #: 9
0
epoch #: 10
0
epoch #: 11
0
epoch #: 12
0
epoch #: 13
0
epoch #: 14
0
epoch #: 15
0
epoch #: 16
0
epoch #: 17
0
epoch #: 18
0
epoch #: 19
0
epoch #: 20
0
epoch #: 21
0
epoch #: 22
0
epoch #: 23
0
epoch #: 24
0
epoch #: 25
0
epoch #: 26
0
epoch #: 27
0
epoch #: 28
0
epoch #: 29
0
epoch #: 30
0
epoch #: 31
0
epoch #: 32
0
epoch #: 33
0
epoch #: 34
0
epoch #: 35
0
epoch #: 36
0
epoch #: 37
0
epoch #: 38
0
epoch #: 39
0
epoch #: 40
0
epoch #: 41
0
epoch #: 42
0
epoch #: 43
0
epoch #: 44
0
epoch #: 45
0
epoch #: 46
0
epoch #: 47
0
epoch #: 48
0
epoch #: 49
0
epoch #: 50
0
epoch #: 51
0
epoch #: 52
0
epoch #: 53
0
epoch #: 54
0
epoch #: 55
0
epoch #: 56
0
epoch #: 57
0
epoch #: 58
0
epoch #: 59
0
epoch #: 60
0
epoch #: 61
0
epoch #: 62
0
epoch #: 63
0
epoch #: 64
0
epoch #: 65
0
epoch #: 66
0
epoch #: 67
0
epoch #: 68
0
epoch #: 69
0
epoch #: 70
0
epoch #: 71
0


In [2]:
for _ in range(300):
    batchSize = 64
    text = '我就是来测试一下，不会带有什么目的，纯粹的测试文档'
    texts = [text[:] for _ in range(batchSize)]
    batchData = tokz(texts, padding=True, return_tensors='pt').to(bert.device)

    sent_vecs_1 = bert(**batchData).pooler_output
    sent_vecs_2 = bert(**batchData).pooler_output

    batchSize, hidden_nums = sent_vecs_1.shape
    combined_sent_vecs = torch.concat([sent_vecs_1, sent_vecs_2], dim=-1) # (batchSize, hidden_nums*2)
    combined_sent_vecs = combined_sent_vecs.view(batchSize*2, hidden_nums) # (batchSize*2, hidden_nums)
    loss = criterion(combined_sent_vecs)
    
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    print(f'epoch #: {_}')

epoch #: 0
epoch #: 1
epoch #: 2
epoch #: 3
epoch #: 4
epoch #: 5
epoch #: 6
epoch #: 7
epoch #: 8
epoch #: 9
epoch #: 10
epoch #: 11
epoch #: 12
epoch #: 13
epoch #: 14
epoch #: 15
epoch #: 16
epoch #: 17
epoch #: 18
epoch #: 19
epoch #: 20
epoch #: 21
epoch #: 22
epoch #: 23
epoch #: 24
epoch #: 25
epoch #: 26
epoch #: 27
epoch #: 28
epoch #: 29
epoch #: 30
epoch #: 31
epoch #: 32
epoch #: 33


KeyboardInterrupt: 

In [1]:
BATCH_SPLIT = 4
for _ in range(300):
    batchSize = 60
    text = '我就是来测试一下，不会带有什么目的，纯粹的测试文档'
    texts = [text[:] for _ in range(batchSize)]
    batchData = tokz(texts, padding=True, return_tensors='pt').to(bert.device)

    sent_vecs_1 = bert(**batchData).pooler_output
    sent_vecs_2 = bert(**batchData).pooler_output

    batchSize, hidden_nums = sent_vecs_1.shape
    combined_sent_vecs = torch.concat([sent_vecs_1, sent_vecs_2], dim=-1) # (batchSize, hidden_nums*2)
    combined_sent_vecs = combined_sent_vecs.view(batchSize*2, hidden_nums) # (batchSize*2, hidden_nums)

    sample_size = combined_sent_vecs.shape[0] # sample_size = batchSize * 2
    assert sample_size % BATCH_SPLIT == 0
    sub_sample_size = sample_size // BATCH_SPLIT   # sub_sample_size: the size of samples in each part

    for i in range(0, sample_size, sub_sample_size):
        print(i // sub_sample_size)
        start = i
        end = i + sub_sample_size
        # sub_combined_sent_vecs = combined_sent_vecs[start:end, :]   # (sub_sample_size, hidden_nums)
        avg_sub_loss = criterion(start, end, combined_sent_vecs.clone(), reduction='mean')
        # print(avg_sub_loss)
        avg_sub_loss.backward()

    optimizer.step()
    optimizer.zero_grad()
    print(f'epoch #: {_}')

NameError: name 'tokz' is not defined

In [11]:
loss_module

<module 'loss_module' from 'd:\\FAQ_PROJECT\\FAQ project\\loss_module\\__init__.py'>

In [ ]:
output = bert(**batchData)

In [ ]:
output.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [19]:
from transformers import BertModel, BertConfig, BertTokenizer

In [17]:
%pwd

'd:\\FAQ_PROJECT\\FAQ project'

In [18]:
simbert = BertModel.from_pretrained('./tmp_data/model_checkpoint/simbert_SimCSE/')

In [21]:
tokz = BertTokenizer.from_pretrained('WangZeJun/simbert-base-chinese')

In [24]:
# 1. 检查代码，是否loss中有错误的计算
# 2. 如果没问题，尝试将代码上传到云端计算
# 3. 使用supervised simcse
# 4. 使用supervised sbert (+R-dropout)

8640

In [14]:
import torch
a = torch.ones(3,2)
b = torch.zeros(3,2)

a_and_b = torch.concat([a,b],dim=-1)
print(a_and_b)
a_and_b.view(6, 2)

tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]])


tensor([[1., 1.],
        [0., 0.],
        [1., 1.],
        [0., 0.],
        [1., 1.],
        [0., 0.]])

In [16]:
a = torch.arange(10)
a.view(2,5), a.view(2,5).argmax(dim=-1)

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([4, 4]))

In [21]:
a.detach().cpu().numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [56]:
l = []

In [58]:
l.append(a)

In [59]:
torch.concat(l,dim=0)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
def test(a=1, *args,**kwargs):
    print(args)
    print(kwargs)
    print(a)

def extend(func):

    class extend:

        def __init__(self, *args, **Kwargs):
            self.k = 100
            pass

        def test_sth(self, *args, **kwargs):
            func(*args, **kwargs)
    return extend

In [87]:
g = extend(test)()

In [88]:
g.test_sth(10, 11, b=1)

(11,)
{'b': 1}
10


In [91]:
from torch import nn
criterion = nn.CrossEntropyLoss(reduction='mean')

In [117]:
import torch
from torch.nn import functional as F

In [115]:
torch.randint(0,3, (5,))

tensor([2, 1, 1, 1, 1])

In [107]:
nn.modules.loss._Loss
# kldiv和nllloss中的Input都是logSoftmax(logits)处理后的数据，也就是输入都是log_probability; 而不是直接输入的数据

torch.nn.modules.loss._Loss

In [146]:
a = torch.arange(10).view(2,5).float()
b = torch.randint(0,20,(2,5)).float()
a, b

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 tensor([[13.,  6.,  4.,  7.,  4.],
         [ 5.,  7.,  9., 17., 18.]]))

In [147]:
log_prob1 = F.log_softmax(a, dim=-1)    # pred
log_prob2 = F.log_softmax(b, dim=-1)    # true/label
log_prob1, log_prob2

(tensor([[-4.4519, -3.4519, -2.4519, -1.4519, -0.4519],
         [-4.4519, -3.4519, -2.4519, -1.4519, -0.4519]]),
 tensor([[-3.6307e-03, -7.0036e+00, -9.0036e+00, -6.0036e+00, -9.0036e+00],
         [-1.3313e+01, -1.1313e+01, -9.3134e+00, -1.3134e+00, -3.1337e-01]]))

In [149]:
log_prob1.exp() * (log_prob1 - log_prob2)

tensor([[-0.0519,  0.1125,  0.5643,  1.0657,  5.4424],
        [ 0.1033,  0.2491,  0.5910, -0.0324, -0.0882]])

In [152]:
criterion = nn.KLDivLoss(reduction='none', log_target=True)

In [169]:
criterion(log_prob2, log_prob1)

tensor([[-0.0519,  0.1125,  0.5643,  1.0657,  5.4424],
        [ 0.1033,  0.2491,  0.5910, -0.0324, -0.0882]])

In [154]:
input = F.log_softmax(torch.randn(3, 5, requires_grad=True))
target = F.log_softmax(torch.rand(3, 5))

C:\Users\86151\AppData\Local\Temp\ipykernel_9196\4123133844.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  input = F.log_softmax(torch.randn(3, 5, requires_grad=True))
C:\Users\86151\AppData\Local\Temp\ipykernel_9196\4123133844.py:2: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  target = F.log_softmax(torch.rand(3, 5))


In [167]:
target.exp() * (target - input)

tensor([[ 0.1166,  0.0640, -0.0882,  0.1450, -0.0973],
        [-0.0111, -0.1570,  0.2012, -0.0390,  0.2993],
        [-0.0507,  0.0694,  0.1274,  0.0487, -0.1060]], grad_fn=<MulBackward0>)

In [168]:
criterion(input, target)

tensor([[ 0.1166,  0.0640, -0.0882,  0.1450, -0.0973],
        [-0.0111, -0.1570,  0.2012, -0.0390,  0.2993],
        [-0.0507,  0.0694,  0.1274,  0.0487, -0.1060]],
       grad_fn=<KlDivBackward0>)

In [174]:
a.flatten().repeat_interleave(2, dim=0)

tensor([0., 0., 1., 1., 2., 2., 3., 3., 4., 4., 5., 5., 6., 6., 7., 7., 8., 8.,
        9., 9.])

In [2]:
class parent:
    def __init__(self):
        pass

class child(parent):
    def __init__(self):
        pass

In [3]:
p = parent()
c = child()

False